### ISSUE TITLE
Ukrainian localization

### ISSUE THREAD

**Issue by a-polivanchuk** [TEA-ebook/teabook-reader-ffox-app#19]
I'd like to translate this app into Ukrainian.
Please, create file for localization.

Thanks!

**Comment by johanpoirier** [comment]
Hi @stenox and thanks for your proposition!

You can review the guidelines for contributing to this repository here : https://github.com/TEA-ebook/teabook-reader-ffox-app/blob/master/CONTRIBUTING.md.

Then fork this repository and checkout the following branch https://github.com/TEA-ebook/teabook-reader-ffox-app/tree/dev/ukrainian and start to edit those files :
 - https://github.com/TEA-ebook/teabook-reader-ffox-app/blob/dev/ukrainian/app/locales/uk.l20n
 - https://github.com/TEA-ebook/teabook-reader-ffox-app/blob/dev/ukrainian/app/manifest.webapp#L32

Once you're done, you can submit a PR from your dev/ukrainian branch.
